version: "3.9"

services:
  k2rebuild:
    image: k2rebuild:x86
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./tools:/tools
      - ./output:/repo/output
    tty: true
    stdin_open: true
